# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180420_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='creators_name',
            field=models.CharField(default='TravelWithFriends', max_length=255),
            preserve_default=False,
        ),
    ]
